import React from 'react';
import { Code, Github } from 'lucide-react';
import { 
  SiSharp, 
  SiPhp, 
  SiNextdotjs, 
  SiReact, 
  SiAngular, 
  SiJquery, 
  SiNodedotjs, 
  SiDotnet, 
  SiCodeigniter, 
  SiMysql, 
  SiBootstrap, 
  SiTailwindcss, 
  SiWordpress, 
  SiGithubactions, 
  SiJira, 
  SiOpenai, 
  SiGoogle, 
  SiSupabase, 
  SiVercel, 
  SiCloudflare,
} from 'react-icons/si';

// Skill icon mapping with colors
export const skillIcons: Record<string, { icon: React.ComponentType<{ className?: string }>, color: string }> = {
  'C#': { icon: SiSharp, color: '#239120' },
  'PowerShell': { icon: Code, color: '#012456' },
  'PHP': { icon: SiPhp, color: '#777BB4' },
  'Next.js': { icon: SiNextdotjs, color: '#000000' },
  'React': { icon: SiReact, color: '#61DAFB' },
  'Angular': { icon: SiAngular, color: '#DD0031' },
  'AngularJS': { icon: SiAngular, color: '#E23237' },
  'jQuery': { icon: SiJquery, color: '#0769AD' },
  'Node.js': { icon: SiNodedotjs, color: '#339933' },
  '.NET Framework MVC': { icon: SiDotnet, color: '#512BD4' },
  '.NET 6': { icon: SiDotnet, color: '#512BD4' },
  'CodeIgniter 4': { icon: SiCodeigniter, color: '#EF4223' },
  'Playwright': { icon: Code, color: '#2EAD33' },
  'xUnit': { icon: Code, color: '#8B5CF6' },
  'SQL': { icon: Code, color: '#336791' },
  'MySQL': { icon: SiMysql, color: '#4479A1' },
  'Bootstrap 3': { icon: SiBootstrap, color: '#7952B3' },
  'Bootstrap 4': { icon: SiBootstrap, color: '#7952B3' },
  'Tailwind': { icon: SiTailwindcss, color: '#06B6D4' },
  'WordPress': { icon: SiWordpress, color: '#21759B' },
  'TinaCMS': { icon: Code, color: '#EC4815' },
  'VMs': { icon: Code, color: '#0078D4' },
  'App Service': { icon: Code, color: '#0078D4' },
  'Key Vault': { icon: Code, color: '#0078D4' },
  'App Insights': { icon: Code, color: '#0078D4' },
  'Bicep': { icon: Code, color: '#0078D4' },
  'Blob Storage': { icon: Code, color: '#0078D4' },
  'Entra ID': { icon: Code, color: '#0078D4' },
  'Container Apps': { icon: Code, color: '#0078D4' },
  'Function Apps': { icon: Code, color: '#0078D4' },
  'Azure Pipelines': { icon: Code, color: '#0078D4' },
  'GitHub Actions': { icon: SiGithubactions, color: '#2088FF' },
  'DevOps': { icon: Code, color: '#0E8E3E' },
  'GitHub Issues': { icon: Github, color: '#181717' },
  'Jira': { icon: SiJira, color: '#0052CC' },
  'ChatGPT': { icon: SiOpenai, color: '#412991' },
  'Gemini': { icon: SiGoogle, color: '#4285F4' },
  'n8n': { icon: Code, color: '#FF6D5A' },
  'Cursor': { icon: Code, color: '#000000' },
  'Supabase': { icon: SiSupabase, color: '#3ECF8E' },
  'Vercel': { icon: SiVercel, color: '#000000' },
  'Azure Front Door': { icon: Code, color: '#0078D4' },
  'Cloudflare': { icon: SiCloudflare, color: '#F38020' },
};

